### ISSUE TITLE
error "sbt assembly" for "chapter-up-and-running"

### ISSUE THREAD

**Issue by asethia** [RayRoestenburg/akka-in-action#28]
Hi,

After running command "sbt assembly" for "chapter-up-and-running", I am getting following error:

downloading http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/test-agent/0.13.7/jars/test-agent.jar ...
        [SUCCESSFUL ] org.scala-sbt#test-agent;0.13.7!test-agent.jar (1784ms)
downloading http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/apply-macro/0.13.7/jars/apply-macro.jar ...
        [SUCCESSFUL ] org.scala-sbt#apply-macro;0.13.7!apply-macro.jar (2823ms)
:: retrieving :: org.scala-sbt#boot-app
        confs: [default]
        51 artifacts copied, 0 already retrieved (15709kB/890ms)
java.lang.IllegalArgumentException: URI has an authority component
        at java.io.File.<init>(File.java:423)
        at sbt.Classpaths$.sbt$Classpaths$$bootRepository(Defaults.scala:1699)
        at sbt.Classpaths$$anonfun$appRepositories$1.apply(Defaults.scala:1670)
        at sbt.Classpaths$$anonfun$appRepositories$1.apply(Defaults.scala:1670)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at sbt.Classpaths$.appRepositories(Defaults.scala:1670)
        at sbt.Classpaths$$anonfun$41.apply(Defaults.scala:1065)
        at sbt.Classpaths$$anonfun$41.apply(Defaults.scala:1065)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
        at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
        at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
        at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] java.lang.IllegalArgumentException: URI has an authority component
[error] Use 'last' for the full log.

Please can someone help me here.

OS: Windows 7 64 bit
sbt launcher version 0.13.7
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)

Regards,
Arun

**Comment by RayRoestenburg** [comment]
Works on Mac OSX, I have been fixing quite a lot of version changes, so please check again.

**Comment by RayRoestenburg** [comment]
Have not heard back so closing this issue.
